# Generated by Django 3.2.6 on 2021-08-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=255, null=True, verbose_name='Rate Name')),
                ('first', models.FloatField(null=True, verbose_name='1st Reading (kWh)')),
                ('second', models.FloatField(null=True, verbose_name='2st Reading (kWh)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='energy.customer')),
            ],
        ),
    ]
