# Generated by Django 3.2.6 on 2021-08-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='second',
            field=models.FloatField(null=True, verbose_name='2nd Reading (kWh)'),
        ),
    ]
