# Generated by Django 3.2.6 on 2021-08-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_auto_20210810_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='energy_consumed',
            field=models.FloatField(blank=True, null=True, verbose_name='Energy Consumption'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Energy cost'),
        ),
    ]
