# Generated by Django 3.2.6 on 2021-08-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_auto_20210810_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
