# Generated by Django 3.2.6 on 2021-08-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0009_alter_consumption_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='cost',
            field=models.FloatField(blank=True, default=models.FloatField(null=True, verbose_name='1st Reading (kWh)'), null=True),
        ),
    ]
