# Generated by Django 3.2.6 on 2021-08-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0010_alter_consumption_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='cost',
        ),
    ]
