# Generated by Django 3.2.6 on 2021-08-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0011_remove_consumption_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Rate Cost'),
        ),
    ]
