# Generated by Django 3.2.6 on 2021-08-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0012_consumption_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='consumption',
            field=models.FloatField(blank=True, null=True, verbose_name='Energy Consumption'),
        ),
    ]
